### PR TITLE
Fixes Unequal Group Sizes #108

### LINKED ISSUE #108: Need to handle unequal group sizes.
Presently, if one sets up an experiment with 12 animals, 2 groups, and 5 animals per cage, it will allow 10 animals to be RFID chipped, and put 10 hamsters in 2 cages (5/cage). The remaining 2 animals have been trimmed off the experiment.

### PR DESCRIPTION
**Pull request by rc10283**
Fixes #108.

### CODE REVIEW

**Comment by kate-holdener** [comment]
How did you test this fix?

**Comment by loganwyas** [comment]
@rc10283 Please describe the changes that were made to the code and how these changes relate to the linked issue.

**Comment by rc10283** [comment]
Group sizes were allowed to be unequal, the example given is 12 animals 2 groups with 5 animals per cage that would have the final 2 animals stripped from the experiment. Using a conditional, I wrote that if the total number of animals, is greater than the animals per cage * the number of cages than a unequal group size warning would appear an the investigator would be asked to reenter the info. Earlier, I did not see a merge conflict that had two warning labels listed as 3, i instead changed my warning of unequal group sizes to label 4. If you have any concerns or anything else the issue should fix please let me know.

**Comment by loganwyas** [comment]
@rc10283 With the example given, I receive a blank warning message:
image

**Comment by rc10283** [comment]
Screen Shot 2023-10-10 at 12 53 51 PM

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
