### PR TITLE
issue serial port simulator

### LINKED ISSUE #112: Create/find serial port signal simulator
We do not have the proper hardware to test serial port signals being sent (for RFID, scales, etc.), and we need a way to properly test this functionality in our app.

### PR DESCRIPTION
**Pull request by stanleyyang2001**
Fixes #112 

A new GUI, SerialSimulator, was added in the map_rfid.py file that allow user to download the needed ports to simulate writing to and reading from the downloaded virtual ports. 

The changes were implemented because Mouser application requires functionality that allows data transfer from other devices to Mouser application through serial port connection. However, our team haven't have the chance to use actual hardware required for developing. Therefore, a simulator that simulate how serial port connections would behave in such circumstances is needed.

The changes were implemented with new GUI that can be accessed from a button in SerialSelection GUI. For new users that haven't downloaded the virtual serial ports yet, a prompt that asks if the user would like to download the virtual serial port will appear and lead the user to the download site when the user press yes. After that, a new GUI will create that contains three parts: text display, input entry, and serial ports drop down selection. The drop-down list contains all virtual serial ports available to be selected and write to once the user selects the port and press the confirm button. The user can then write to the serial port by entering the desired message and press the sent button. Lastly, the message that the user write to the serial port will be read by the other virtual serial port and displayed onto the text display. 

**Screenshots that show the changes (if applicable):**
[Uploading issue_serial_port_simulator.pdf…]()

### CODE REVIEW

**Comment by stanleyyang2001** [comment]
@loganwyas That's odd. I'm running on Windows 10 and PySerial did list all my com ports and virtual ports. Are you sure that you have the virtual ports downloaded as the simulator only shows the specific virtual ports downloaded from com0com.

**Comment by loganwyas** [comment]
@stanleyyang2001 This is what I am seeing under my device manager, so I would assume that they are downloaded.

image

**Comment by stanleyyang2001** [comment]
@loganwyas Try removing it and downloading it again. On my device there's only the com0com-serial port emulator (COM4) and com0com-serial port emulator (COM5).

**Comment by loganwyas** [comment]
I was able to get it working, thanks

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
