### PR TITLE
Scroll Bar Data Collection

### LINKED ISSUE #167: Add scroll bar to data collection table
**Should not be worked on until #150 is done**

When there's a large number of animals that exists in an experiment, the table in the data collection page will get overflooded by the animal id. Add a scroll bar to the table in the cause when there's a large amount of animals instead of letting the row adding up.

### PR DESCRIPTION
**Pull request by rc10283**
Fixes #167 

**What was changed?**

Added A scrollbar to data collection in case of large group sizes.

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
Added the scrollbar logic that is used in other pages to the Data Collection page

**Why was it changed?**
Bunched up with larger group sizes that would exceed the size of the frame, allows users to see all animals in large group size.

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
#167

**How was it changed?**

No code was changed only added. Added the lines needed for CTkCanvas and scrollbar.
**Screenshots that show the changes (if applicable):**

Screen Shot 2024-03-04 at 1 04 33 PM

### CODE REVIEW

**Comment by loganwyas** [comment]
@rc10283 What is the progress on making the requested changes?

**Comment by rc10283** [comment]
What Changes?

**Comment by loganwyas** [comment]
12 days ago, I made a comment on this PR that I couldn't run the application due to import errors.

**Review by loganwyas — CHANGES_REQUESTED** [review]

**Review by rc10283 — COMMENTED** [review]
Updated Imports

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
