### PR TITLE
uploading serial port setting draft

### LINKED ISSUE #149: Add proper serial port settings
**Note: should not be completed until issue #150 is closed**

The user needs to have flexibility in regards to the settings for serial ports. This means that they should be able to select the specifications of the device(s) they are using to enter in data. This includes parity, data bits, stop bits, flow control, and baud rate (similar to the picture below)

mouser-serial-port

What is required for this issue to be completed:
- [x] Reconfigure the current serial port controller to include the above settings
- [x] Saving settings
  - [x] Allow users to name specific configurations when saving
  - [x] Save all of the configurations to the user's system (**not** on individual experiments or the repository), without modifying the registry
  - [x] Display a clickable list of the current configurations
  - [x] Ability edit a previously created configuration
  - [x] Import/export options of all configurations (probably just CSV)
- [x] Add a "Settings" > "Serial Ports" option in the menu bar that opens the dialog (currently in Map RFID, should be instead moved here)

### PR DESCRIPTION
**Pull request by stanleyyang2001**
Fixes #149 

**What was changed?**

A new setting page for serial port is added to the menu bar. The serial port setting consists of two different frame. The first is a summary of the serial port setting that's currently in used. The second is a page that allows user to choose existing serial port setting configuration to use or edit, or to create a new setting configuration.

**Why was it changed?**

It's needed so that user would have the ability to access the serial port setting of the program at any time instead of at certain pages.

**How was it changed?**

A new setting menu is implemented that gave access to the serial port setting GUI. A new file directory was created to place the serial port configuration.

**Screenshots that show the changes (if applicable):**
[Untitled document (1).pdf](https://github.com/oss-slu/Mouser/files/14894939/Untitled.document.1.pdf)
[Untitled document.pdf](https://github.com/oss-slu/Mouser/files/14894940/Untitled.document.pdf)

### CODE REVIEW

**Comment by loganwyas** [comment]
@stanleyyang2001 What's the progress on this?

**Comment by stanleyyang2001** [comment]
@loganwyas The requirement is done now, just have things that needs to be fixed in other issues

**Comment by loganwyas** [comment]
@stanleyyang2001 There are a few issues that should be fixed before being merged:

- The Pylint does not pass, mainly due to "serial_port_settings.py". Please look at the workflow details to see why it did not pass.
- The "database_apis" and "databases/experiments" folders are from an old version of the project, and I am not sure how they got there, so they should be deleted.
- There are a bunch of binary files (such as "test unique id" and "test password_Protected.mouser") that should not be present on the repository, so they should also be deleted.

**Comment by stanleyyang2001** [comment]
@loganwyas Everything is fixed now, just needs the review.

**Comment by stanleyyang2001** [comment]
@loganwyas Should be good now.

**Review by loganwyas — APPROVED** [review]

**Pull request merged**
